MAP_W = 120
MAP_H = 120
ARENA_RADIUS = 60
N_PLAYERS = 5
MATCH_SECONDS = 180
TICK_HZ = 30
DECISION_HZ = 10

START_AREA_FRAC = 0.03
BASE_SPEED = 10
SPEED_STEP = 1
SPEED_STEP_PCT = 5

RESPAWN_DELAY_S = 3
RESPAWN_MIN_DIST = 20
ACT_TIMEOUT_MS = 50
LOCAL_VIEW = 31

KILL_BOOST_MULT = 1.5        # speed multiplier a killer gets
KILL_BOOST_S = 5             # seconds the boost lasts
MAX_SPEED = 29               # cells/s hard cap (keeps <=1 cell per tick)

# derived
STEP_PER_DECISION = TICK_HZ // DECISION_HZ
TOTAL_TICKS = MATCH_SECONDS * TICK_HZ
RESPAWN_DELAY_TICKS = RESPAWN_DELAY_S * TICK_HZ
KILL_BOOST_TICKS = KILL_BOOST_S * TICK_HZ
ARENA_CENTER = ((MAP_H - 1) / 2, (MAP_W - 1) / 2)
SPAWN_RING_FRAC = 0.60
